import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";

// components
import Header from "@/components/ui/Header";
import Pagetrans from "@/components/pagetrans";
import Staireff from "@/components/StairEff";

const JetBrainsMono = JetBrains_Mono({ 
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>My Next.js App</title>
      </head>
      <body className={JetBrainsMono.variable}>
        <Header />
        <Staireff />
        <Pagetrans>{children}</Pagetrans>
        <SpeedInsights />
      </body>
    </html>
  );
}
