import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/ui/Header";
import pagetrans from "@/components/pagetrans";
import staireff from "@/components/StairEff";

const JetBrainsMono = JetBrains_Mono({ 
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={JetBrainsMono.variable}>
        <Header />
        <staireff />
        <pagetrans>{children}</pagetrans>
      </body>
    </html>
  );
}
